### ISSUE TITLE
Ability to Query reference fields in objects

### ISSUE THREAD

**Issue by bazarnov** [StevenMMortimer/salesforcer#100]
Hi, the answer is probably "You can't, unless the data is populated inside the object" however the question is still here.
 
Can I use sf_query() in order to pull out the data from object X that has reference fields to other objects inside? 

Tried the standard APEX practice == "SELECT ...., $my_field__r  LIMIT 100", 
where $my_field__r = reference field to another object.

Thank you for your answer.

**Comment by StevenMMortimer** [comment]
@bazarnov When you say "reference fields", do you mean fields on another object that has a relationship to another object? If so, I have heard them referred to as "relationship queries" and they are supported like so: 

**Child-to-Parent**
```r
sf_query("SELECT Name, Account.Id, Account.Name FROM Contact")
```

\- or -

**Parent-to-Child**
```r
sf_query("SELECT Name, (SELECT LastName FROM Contacts) FROM Account")
```

**Comment by bazarnov** [comment]
Perfect, thanks.

________________________________

**Comment by StevenMMortimer** [comment]
Great. Please note that the Bulk Query APIs do not support relationship queries, so you will need to use the REST or SOAP APIs.
