### ISSUE TITLE
salesforcer removed from CRAN

### ISSUE THREAD

**Issue by egde** [StevenMMortimer/salesforcer#101]
Hi there,

thanks for providing this library to access salesforce and the Force environment! Unfortunately the library has been removed from the CRAN repository, due to some errors in the check: [https://cran-archive.r-project.org/web/checks/2021/2021-06-23_check_results_salesforcer.html]

The missing RForcecom library is the root cause, I guess?

**Comment by StevenMMortimer** [comment]
I have fixed the issues relating to RForcecom causing the package to be removed from CRAN. The CRAN team confirmed around 9am on Tuesday, July 6 that the package was approved and now moving through the pipeline. Based on prior experience, my guess is that the binaries will be compiled and built by Friday, July 9.
