### ISSUE TITLE
INVALID_TYPE_FOR_OPERATION: entity type does not support merge

### ISSUE THREAD

**Issue by erdemakkas** [StevenMMortimer/salesforcer#102]
Thank you for the great package.

When I try to merge 2 opportunity items I receive below response:

```
merge_res <- sf_merge(master_id = to_merge[1],
+                       victim_ids = to_merge[2],
+                       object_name = "Opportunity",verbose=TRUE)
Request failed [500]. Retrying in 1.9 seconds...
Request failed [500]. Retrying in 3 seconds...

--HTTP Request----------------
POST https://svpct--svpfull.my.salesforce.com/services/Soap/u/48.0
--Headers---------------------
Accept: application/json, text/xml, application/xml, */*; SOAPAction: merge; Content-Type: text/xml; Authorization: Bearer 00D3C00000057Z3!AQIAQOM6Yz9S1Ks2a9DnKwCArmcKFmMechzekV3vQJALlea5rVwIEZ535ObTNUOaT0SSg6LUxSYscLXBkEjxqeFYz72iQMkW
--Body------------------------
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:urn="urn:partner.soap.sforce.com" xmlns:urn1="urn:sobject.partner.soap.sforce.com">
  <soapenv:Header>
    <urn:SessionHeader>
      <urn:sessionId>00D3C00000057Z3!AQIAQOM6Yz9S1Ks2a9DnKwCArmcKFmMechzekV3vQJALlea5rVwIEZ535ObTNUOaT0SSg6LUxSYscLXBkEjxqeFYz72iQMkW</urn:sessionId>
    </urn:SessionHeader>
  </soapenv:Header>
  <soapenv:Body>
    <urn:merge>
      <mergeRequest xsi:type="MergeRequest">
        <masterRecord xsi:type="Opportunity">
          <Id>0061I00000EkzqJQAR</Id>
        </masterRecord>
        <recordToMergeIds>0061I00000GdVQwQAN</recordToMergeIds>
      </mergeRequest>
    </urn:merge>
  </soapenv:Body>
</soapenv:Envelope>
Error in catch_errors(httr_response) : 
  INVALID_TYPE_FOR_OPERATION: entity type does not support merge
```

**Comment by StevenMMortimer** [comment]
@erdemakkas The API's merge operation only supports merging records from the following objects: Lead, Contact, Account, Person Account, and Individual. <sup>[1]</sup>. This has been documented on a few different places across the web. The most detailed hypotheses for why Salesforce does not provide this functionality is noted in this StackExchange post: https://salesforce.stackexchange.com/a/75302

**Next Steps**: You can use the {salesforcer} package to update the master (target) record and then delete the victim record. The alternative is to use an app available on the app exchange that has written its own custom code to merge the opportunities. The former option gives you more control, but also is more work.

[1] https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_merge.htm

**Comment by erdemakkas** [comment]
@StevenMMortimer  Thank you very much for the help and clarification.

> 
> 
> @erdemakkas The API's merge operation only supports merging records from the following objects: Lead, Contact, Account, Person Account, and Individual. [1]. This has been documented on a few different places across the web. The most detailed hypotheses for why Salesforce does not provide this functionality is noted in this StackExchange post: https://salesforce.stackexchange.com/a/75302
> 
> **Next Steps**: You can use the {salesforcer} package to update the master (target) record and then delete the victim record. The alternative is to use an app available on the app exchange that has written its own custom code to merge the opportunities. The former option gives you more control, but also is more work.
> 
> [1] https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_merge.htm
