### ISSUE TITLE
Bad Request (HTTP 400). Failed to get an access token.

### ISSUE THREAD

**Issue by po-omena** [StevenMMortimer/salesforcer#108]
I've been using the salesforcer package for a while now but suddenly i'm getting this error message:
Authentication complete.
Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Bad Request (HTTP 400). Failed to get an access token.
I'm using a custom salesforce server and it is currently on my sf_auth parameter as login-url
(i.e.: sf_auth(login_url = url))

**Comment by StevenMMortimer** [comment]
@po-omena Thanks for flagging. Is this still an issue or could you provide a screenshot with more details? Happy to help as needed.

**Comment by StevenMMortimer** [comment]
@po-omena Closing for now. Feel free to re-open if this issue persists.
