### ISSUE TITLE
setPassword 

### ISSUE THREAD

**Issue by nataliagalant** [StevenMMortimer/salesforcer#11]
wondering if it's possible to make admin utility calls like setPassword() using this package, or using R in general.

**Comment by StevenMMortimer** [comment]
@nataliagalant Definitely possible. I'll add as a feature request. It would be implemented similarly to the existing utility calls in the package.

**Comment by nataliagalant** [comment]
Awesome, would make the package even better than it already is! 

I thought it would be similar to these calls and had already looked into those but I noticed that the setPassword call is not supported by the sales force REST API (either that or I couldn't find the endpoint in the documentation). 

Would this call be made through a chatter base URL? something like the one in sf_user_info:
https://na8.salesforce.com/services/data/<api_version>/chatter/users/me ?
