### ISSUE TITLE
Will Salesforce's MFA requirement impact this package?

### ISSUE THREAD

**Issue by klaw2** [StevenMMortimer/salesforcer#113]
Beginning in Feb 2022 Salesforce is going to require customers to enable multi-factor authentication in order to access SF products.

https://admin.salesforce.com/blog/2021/everything-admins-need-to-know-about-the-mfa-requirement

Do you suspect that the sf_auth() function will be impacted by this at all?

**Comment by StevenMMortimer** [comment]
@klaw2 Great question. The {salesforcer} package supports Single Sign-on (SSO) via OAuth 2.0. My guess is that the MFA will simply require an extra step in the browser when you first authenticate. Note that, if you login via OAuth 2.0 and authenticate via the browser, the OAuth token will be cached in the working directory so you do not need to authenticate through the browser and MFA every single time you use the API.

With the package you have the option to either use the connected app bundled with the package or create your own in your org (recommended). I'd recommend reading the Salesforce documentation to [Create a Connected App](https://help.salesforce.com/s/articleView?id=sf.connected_app_create.htm&type=5) and also taking a look at this issue (https://github.com/StevenMMortimer/salesforcer/issues/107) to see my thoughts while helping another user configure their instance to use Okta to login.

Finally, it's tough for me to debug across other environments, but feel free to reach out with questions or let me know if you found a certain trick or hack that's needed to make things work. I'm happy to improve upon the existing functionality and other users can benefit.

**Comment by klaw2** [comment]
Thank you, that's helpful to know. Will definitely follow up if there are any additional steps that require some sort of workaround.

**Comment by StevenMMortimer** [comment]
I've updated the documentation [here](https://stevenmmortimer.github.io/salesforcer/articles/getting-started.html#authentication) to reflect this change on Salesforce's end. I've also given kudos to @klaw2 in the [NEWS for v1.0.1](https://stevenmmortimer.github.io/salesforcer/news/index.html#salesforcer-101-release) which pushed the updated documentation. I'll close this issue for now and we can re-open or create new issues, if needed. Thanks again @klaw2!
