### ISSUE TITLE
salesforcer and Shiny

### ISSUE THREAD

**Issue by JacobNord** [StevenMMortimer/salesforcer#114]
### Issue description

I tried to run a shiny app that pulls in info using sf_auth() and sf_execute_report() to then created a dashboard with data from salesforce since salesforce doesnt have the same functionality R has. The app works on my computer, but when I push it to a server (shinyapps.io), it fails. My question is if its even possible to use any of the salesforcer functions in a shiny app, or if it will never work due to authentication issues.

**Comment by StevenMMortimer** [comment]
Hi @JacobNord! – Thanks for reaching out. When you're unable to do interactive authentication, such as on a server or Shiny app running on a server, you should save your authentication token as a file and then copy it onto the server. As long as the token is in the root directory of your executing code, `sf_auth()` will automatically authenticate. There are two methods where you copy a file onto your server and each method will achieve what you need:

1. **`.httr-oauth-salesforcer`**: This file is created in the root of your project when you complete the web-based authentication process. Simply copy/paste it into the root of your project on the server. `sf_auth()` looks for this file and, if it already exists, it will authenticate using that information. Nothing else to do on your part.

2. **A token ending in .rds**: Alternatively, you could explicitly save the token information and load it using `sf_auth(token="/my-token.rds")`. This process is outlined here: https://github.com/StevenMMortimer/salesforcer/issues/28#issuecomment-513762919

In that comment linked above, I reference an old but still relevant article from Jenny Bryan about how OAuth tokens are used to authenticate R with Google Sheets. The salesforcer package uses this same exact OAuth flow. 
https://rawgit.com/jennybc/googlesheets/master/vignettes/managing-auth-tokens.html

If you're still having trouble, just let me know. I'm happy to help.

**Comment by JNords** [comment]
Hey @StevenMMortimer I believe your comment accomplishes what I want, I just want to make sure I understand how it works.
When first run, `sf_auth()` generates a token which is used to tell SalesForce "Hey i have permission to view and export data from you." That token is stored on my computer and is referred to when I use the package to connect to salesforce so that a new token doesnt have to be generated each time. 

If I save that token in my Shiny app, the app will also have the capability to access salesforce data through the `salesforcer` functions. Is this correct? Additionally, do you know if there are any security issues with having a shiny app that uses my token to view data? Is it possible for someone to get that token and use it and how could I prevent it?

**Comment by JacobNord** [comment]
Sorry, the above comment was from my other GitHub account. 

This worked! When I push my shiny app to shiny apps.io, I also push the token.Rds file created by the process you outlined. The ‘sf_auth()’ argument in my server code automatically authenticates using my token file, and then the app can then use functions like ‘sf_excecute_report()’

As a security measure, do you know if there is a way for a non R user who wants to use my app to get their own token? If that’s possible, I could then give them a file input and they could upload theirs to pass to ‘sf_auth()’

**Comment by StevenMMortimer** [comment]
@JacobNord Apologies for not seeing this until just now :( I think your idea about uploading a token would be a good one, especially if the contents of the Shiny app needs to be limited to only what the user has access to in Salesforce. If not, then you might just want to ask your admin to create a single user with the right scopes/permissions and use that user's token in the app for everyone to use. Let me know if you've already figured this out or need more help. I can take a look in the coming week or two.

**Comment by StevenMMortimer** [comment]
@JacobNord Closing for now. Feel free to re-open if you have more to add on this issue. Thanks!

**Comment by bcaessens** [comment]
Hi Steven (and Jacob),

Although this solution works well, I think it doesn't allow us to have different users log in with their salesforce account. In my case, I have different users, all with a salesforce account. So I would like them to login using their personal account info, and logging them out when they leave. However, as the interactive part doesn't work, this is kind of hard to achieve. 

Kind regards,
Bernie.
