### ISSUE TITLE
'sf_query'

### ISSUE THREAD

**Issue by mthandenisithole** [StevenMMortimer/salesforcer#119]
Hi, 
I have got a problem here, I am trying to pull the data from salesforce to R.
I am using the salesforcer package. I tried using the **sf_query** function to  return specific fields from the same object it doesn't want to return some fields especially if the field name is a 2 words e.g **Account Name,** it only pulled the cellphone & Type fields from the my Org  Accounts object.

Please advise me on what I can do to solve this problem.

**Comment by StevenMMortimer** [comment]
Hi @mthandenisithole! Thanks for reaching out. Please note that you cannot use the field label when writing SOQL (which is what the `sf_query()` function requires as input. You must use the field names (API names) of the fields. You can find these by clicking on Setup and then clicking on `Customize > (Object Name You're Interested In) > Fields` to find the field names. See the screenshots below for how I found them for the Account object in my test org. 

<img width="629" alt="image" src="https://user-images.githubusercontent.com/5299737/161670104-243cd033-037e-4cf4-bcde-941047269163.png">

<img width="922" alt="image" src="https://user-images.githubusercontent.com/5299737/161670137-2f64429c-5226-4c7b-ac5e-e84c6a487e4d.png">

**Comment by StevenMMortimer** [comment]
@mthandenisithole Closing for now. Feel free to re-open if you have more to add on this issue. Thanks!
