### ISSUE TITLE
Connecting R and Salesforce Sandbox Not Working Properly

### ISSUE THREAD

**Issue by Zlado** [StevenMMortimer/salesforcer#125]
### Issue submission checklist

When filing your issue please make an attempt to understand your query and debug a little bit on your own. Below are a few suggestions on how to troubleshoot and document your issue. You may also refer to the [Troubleshooting](https://stevenmmortimer.github.io/salesforcer/articles/supported-queries.html#troubleshooting-1) section of the [Supported Queries vignette](https://stevenmmortimer.github.io/salesforcer/articles/supported-queries.html). Thank you for considering these steps! It will speed up the process of resolving your issue.  

  - [x] I have set `verbose=TRUE` in `sf_query()`.
  
  - [x] I have tried a few different function call arguments to see if I can workaround and/or isolate the issue (e.g. reviewing the output from the "SOAP" vs "REST" or the "Bulk 1.0" vs "Bulk 2.0" or tinkering with the `control` argument in the function call).
  
  - [x] I have taken a look at the query unit tests [test-query.R](./tests/testthat/test-query.R) to see if my type of query has been documented and tested.
  
  - [x] I have considered making a minimal reproducible example using the [**reprex**](http://reprex.tidyverse.org/) package. Details on how to create a reprex are available here: https://www.tidyverse.org/help/#reprex.
  
  - [x] I have included the version of R and any packages that are used (Hint: Simply copy/paste the result of `devtools::session_info()` at the bottom of your issue).
  
----

### Issue description

When calling the production environment for my org, I am able to access all the record data, but would like to switch to a sandbox environment for 'upsert' testing. When switching, I updated to the username, password, sec token, and login URL which is returning successful, but the data is still the production environment data (code snippet below).  

Furthermore, evaluating the "sf_user_info()" command shows my username from the production environment so it doesn't look like the sandbox is being called/authenticated. Referring to Page 220 of the salesforcer documentation, it outlines just updating the URL, but that did not work either. I verified the inputs to sf_auth() were the Sandbox updated variables, so note sure what the issue is here. Have you seen this before?

### CODE
```r
( Production information )
  u_name <- "z@gmail.com"
  pw <- "password"
  sec_token <- "PO2456773223456332" # generated from production environment instance
  Instance_login-url <- "https://login.salesforce.com/"

( Sand Box Information )
  u_name <- "z@gmail.com.cs2616"
  pw <- "password"
  sec_token <- "AKSNBDAIUSBDOAISBD" # generated from sandbox environment 
  Instance_login-url <- "https://cs2616.salesforce.com/"

   session_oauth<-sf_auth(
      username = u_name,
      password = pw,
      security_token = sec_token,
      token=token.rds,
      # login_url = getOption("salesforcer.login_url"),
      login_url = Instance_login_url,
      consumer_key = getOption("salesforcer.consumer_key"),
      consumer_secret = getOption("salesforcer.consumer_secret"),
      callback_url = getOption("salesforcer.callback_url"),
      cache = getOption("salesforcer.httr_oauth_cache"),
      verbose = TRUE
   )
   
   sf_auth()
   sf_user_info() #show user info
```
---

### Session Info

```r
R4.2.2
Rstudio 2022.07.02
OAuth 2.0 authentication
Salesforce Lightning UI
```

**Comment by StevenMMortimer** [comment]
@Zlado Thanks for including all the details. Have you tried logging in using the url `https://test.salesforce.com` instead of directly including the instance subdomain (`https://cs2616.salesforce.com`)?

**Comment by Zlado** [comment]
@StevenMMortimer yes and both did the same. I actually resolved this issue by 1st authenticating with either production or testing environment and then after the second sf_auth() adding a line of code that specifies the login -> _sf_auth(login_url = _Instance_login_url) and it worked just fine. Thanks for helping though!
