### ISSUE TITLE
Question about "Unsupported Legacy API Version"

### ISSUE THREAD

**Issue by jcdewitte** [StevenMMortimer/salesforcer#126]
I hope this message finds you well. I have recently received a communication from Salesforce organization regarding the use of legacy API endpoints. As an admin of an organization actively utilizing the Salesforce Platform SOAP, Bulk, and REST APIs, I have been informed that versions 21.0 through 30.0 of these APIs are no longer supported and immediate action is required before May 2023.

As I understand, I am currently using the BULK 1.0 version to extract data from Salesforce, which may be the source of the issue. Given this, I would appreciate your guidance on whether the library would remain compatible beyond May 2023.

Thank you for your assistance.

Best regards,
Jean-Christophe

**Comment by StevenMMortimer** [comment]
The Bulk API (1.0) is still available using Versions 31.0 to 62.0. It's only a problem if you're calling the Bulk API using Version 30.0 or earlier. This is the same as if you were using the REST or SOAP APIs. The communication could be about anyone making calls using V30 or earlier.

<img width="832" alt="image" src="https://github.com/user-attachments/assets/2698e8b1-26bb-49df-a06a-d83c96b5097b">

https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/bulk_common_api_end_of_life.htm

Sorry for the delay. I hope this is still useful, if needed.
