### ISSUE TITLE
Suppress security token deprecation warning for integration user.

### ISSUE THREAD

**Issue by sprimeaux-nolapublicschools** [StevenMMortimer/salesforcer#128]
For integration users exempted from OAuth flow and multi-factor authentication, it might nice to have a way to suppress this warning:

"The `security_token` argument of `sf_auth()` is deprecated as of salesforcer 1.0.1."

I'm happy to work on this for you if you have a recommended approach.

**Comment by StevenMMortimer** [comment]
Thanks for flagging this was removed on the dev branch a couple years ago (0ddbc33f53f3b679c4a0a869c1abacf6120b7680) but never moved to the main branch and deployed to CRAN. I'll push this change into the next CRAN version.

Sorry for the delay.
