### ISSUE TITLE
Error with Bulk Query After Timeout

### ISSUE THREAD

**Issue by StevenMMortimer** [StevenMMortimer/salesforcer#13]
Often I get a timeout error running the sf_query_bulk() function.

```
Function's Time Limit Exceeded. Aborting Job Now Error in match.arg(api_type) : 'arg' should be one of “Bulk 2.0”
```

It tells me to use the api_type of "Bulk 2.0" but if I try run
sf_query( ..., api_type = "Bulk 2.0")
I get the error
Error in match.arg(api_type) : 'arg' should be one of “REST”, “SOAP”, “Bulk 1.0”

Is there anyway to use Bulk 2.0?

**Comment by StevenMMortimer** [comment]
@r-lister The default number of tries is 100 while waiting 5 seconds between each check on the query status. This means that your query has ~500 seconds, or 8.3 minutes to complete. If not, then it automatically aborts. I would recommend running your query from R and then monitoring it in Salesforce's Bulk API dashboard just to see what it's saying there as well. Your Bulk API dashboard is available at the URL: https://{{your.instance}}.salesforce.com/750

I can check about the ensuing error because it seems like a Bulk 1.0 function is passing something onto a function that is only Bulk 2.0 capable after it determines the query is taking too long.

**Comment by StevenMMortimer** [comment]
The error is that `sf_abort_job_bulk()` is written to only accept Bulk 2.0 as the `api_type`, but it actually does support Bulk 1.0, so we need to remove that restriction so that the function aborts gracefully and without error.

**Comment by StevenMMortimer** [comment]
Making a note to check if `sf_delete_job_bulk()` can delete Bulk 1.0 jobs as well as Bulk 2.0 jobs. It's currently written to only accept Bulk 2.0 jobs as something that can be deleted. 

https://github.com/StevenMMortimer/salesforcer/blob/99b592db313678d69446434b188c8840e7a38152/R/bulk-operation.R#L371

**Comment by r-lister** [comment]
Thanks for looking into this, is there anyway to check on previous bulk api jobs with salesforcer? I'm doing this work for another company and my account only has API access so I can't login to the UI, so I can't see the dashboards or anything.

**Comment by r-lister** [comment]
@StevenMMortimer 
Thanks for adding this in, I've used it briefly and can only seem to get info for jobs that were created on or after the 10th December (7 days ago), is this a limitation in salesforce?
I will work on storing this info permanently in our database if that is the case - and check tomorrow to see if it only gives me the 11th and after

**Comment by r-lister** [comment]
@StevenMMortimer Not to worry, I'll start exporting the dataframe to monitor it over longer periods.
Thanks again for your help

**Comment by r-lister** [comment]
@StevenMMortimer 
Hi Again,
I'm actually having trouble using the function this morning, it worked fine yesterday
`> all_jobs <- sf_get_all_jobs_bulk()
Error in curl::curl_fetch_memory(url, handle = handle) : <url> malformed`
Any idea what's happening?

**Comment by StevenMMortimer** [comment]
@r-lister You will receive curl errors from time to time. Just re-run the function. If you are using in a script, I recommend including a small test query in your script to ensure the API is working before throwing a big query to it.
