### ISSUE TITLE
InvalidSessionId

### ISSUE THREAD

**Issue by yongks** [StevenMMortimer/salesforcer#15]
When I use OAuth2 for authentication, my bulk API 1.0 query works fine.

However, when I use username, password, security token to authenticate, I got 
**"Error in catch_errors(httr_response) : InvalidSessionId: Unable to find session id"** error.

I can confirmed that my authentication works because "sf_user_info()" gave me correct result (which is only possible when authentication is successful. 

I'm using salesforcer 0.1.2, and R version 3.5.1.

**Comment by StevenMMortimer** [comment]
Thanks, @yongks! Did you install the package from CRAN? or from GitHub prior to July 8th, 2018? I believe this issue was fixed and deployed on GitHub after that date. Issue #6 outlines a similar bug report. Let me know if you still have problems after re-installing like this: 

```
remove.packages('salesforcer')
devtools::install_github('StevenMMortimer/salesforcer')
```

**Comment by yongks** [comment]
> Thanks, @yongks! Did you install the package from CRAN? or from GitHub prior to July 8th, 2018? I believe this issue was fixed and deployed on GitHub after that date. Issue #6 outlines a similar bug report. Let me know if you still have problems after re-installing like this:
> 
> ```
> remove.packages('salesforcer')
> devtools::install_github('StevenMMortimer/salesforcer')
> ```

Yes. Problem solved with the github package. Thank you @StevenMMortimer and great work !
