### ISSUE TITLE
sf_auth prevents alternative login_url during OAuth

### ISSUE THREAD

**Issue by weckstm** [StevenMMortimer/salesforcer#17]
When suppplying an alternative login_url to sf_auth during OAuth, it still redirects to login.salesforce.com, which makes it impossible to OAuth to the Sandbox environment (test.salesforce.com).

I am not sure, but I suspect the following section:

```
sf_oauth_endpoints <- oauth_endpoint(request = NULL,
                                           base_url = "https://login.salesforce.com/services/oauth2",
                                           authorize = "authorize", access = "token", revoke = "revoke")
```

**Comment by weckstm** [comment]
It seems like that indeed was the problem. I updated the section and created a pull request.

`sf_oauth_endpoints <- oauth_endpoint(request = NULL,
                                           base_url = paste0(login_url,"/services/oauth2"),
                                           authorize = "authorize", access = "token", revoke = "revoke")`

**Comment by StevenMMortimer** [comment]
@weckstm This fix has now been included in the latest CRAN version of the package (0.1.3)

**Comment by weckstm** [comment]
Yay! 👍
