### ISSUE TITLE
Download Attachment Body Content

### ISSUE THREAD

**Issue by rgustavs** [StevenMMortimer/salesforcer#20]
Hi
Thank you for a great package. Very useful to me.

I would like to download attachment and I am struggling with the final step. 

Here is what I do

`sf_auth()
b <- sf_query("SELECT Body, Name, Id FROM Attachment WHERE ParentId = 'XX'")`

and I get a list of references back
`>glimpse(b)`

`Body <chr> /services/data/v42.0/sobjects/Attachment/00P5700001SCWgXXXX/Body"`
`Name <chr> "Doc.pdf"`
`Id   <chr> "00P570000X"`

How do I download Doc.pdf which is hiding inside /services/data/v42.0/sobjects/Attachment/00P5700001SCWgXXXX/Body?

**Comment by StevenMMortimer** [comment]
@rgustavs The Salesforce documentation is here: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_blob_retrieve.htm

Below is a function I've written called `sf_download_attachment()` that will perform the action of getting the attachment as a binary body and then writing it to disk. I'll add this function to the next CRAN release, for now, just load it in your script and use it as demonstrated below the function.

```
sf_download_attachment <- function(body, name, path = "."){
  resp <- rGET(sprintf("%s%s", salesforcer_state()$instance_url, body))
  f <- file.path(path, name)
  writeBin(content(resp, "raw"), f)
  return(file.exists(f))
}

sf_download_attachment(body = "/services/data/v45.0/sobjects/Attachment/00P6A00000PnNK3UAN/Body", 
                       name = "test.pdf",
                       path = ".")
```

**Comment by StevenMMortimer** [comment]
@rgustavs If you'd like to download all of the attachments at once, then use `mapply()`. Like this: 

```
queried_attachments <- sf_query("SELECT Body, Name
                                 FROM Attachment
                                 WHERE ParentId = '0016A0000035mJ5'")
mapply(sf_download_attachment, queried_attachments$Body, queried_attachments$Name)
```

**Comment by rgustavs** [comment]
wow! thanks for quick response. I will try this first thing in the morning and revert back to you.

**Comment by rgustavs** [comment]
Works like a charm. Many thanks. Also appreciate the login_url fix.

Early adopters, needed the following libraries

library(tidyverse)
library(salesforcer) -> github version, not cran
library(httr)

**Comment by StevenMMortimer** [comment]
@rgustavs The function I prototyped above has now been included in the latest CRAN version of the package (0.1.3)
