### ISSUE TITLE
UNSUPPORTED_API_VERSION: Invalid Api version specified on URL

### ISSUE THREAD

**Issue by pcorvalan** [StevenMMortimer/salesforcer#24]
I've using 0.1.2 without problem, after update to 0.1.3 I got the following error

sf_auth()

user_info <- sf_user_info()

Error in catch_errors(httr_response) : UNSUPPORTED_API_VERSION: Invalid Api version specified on URL.

I tried to use basic auth with user and password it didn't work
I noticed if I use rforcecom.login   with  apiVersion = "45.0" it works.

is it a problem with the api version? how may use an api version using sf_auth() ?

Regards.

**Comment by pcorvalan** [comment]
Maybe is a problem with the end point, When I use rforcecom.login I specify loginURL

rforcecom.login('myuser', 'mypassword',
loginURL = "https://na68.salesforce.com/", apiVersion = "45.0")

**Comment by StevenMMortimer** [comment]
@pcorvalan Can you delete your token created by sf_auth() and then go through the web browser based flow again? I'm wondering if your token was created using v45 and the package has now been upgraded to v46. By "delete your token", there should be a file called `.httr-oauth-salesforcer` in your working directory. Delete that and then run `sf_auth()` again and your web browser should pop open to authenticate again.

You can also specify the login URL when using `sf_auth(login_url = "https://na68.salesforce.com/")` and can check if that makes any difference. Let me know what you run into. 

Sometimes just resetting your R session and removing and re-installing the package again will fix stuff, so hit CTRL+SHIFT+F10 on Windows or CMD+SHIFT+F10 on Mac and then run the following commands: 
```
remove.packages('salesforcer')
install.packages('salesforcer')
```

**Comment by pcorvalan** [comment]
I deleted from my working directory:
.httr-oauth-salesforcer

execute: 
sf_auth()
user_info <- sf_user_info()
got: 
Error in catch_errors(httr_response) : UNSUPPORTED_API_VERSION: Invalid Api version specified on URL

a new token was created:
.httr-oauth-salesforcer

I tried: 
sf_auth(login_url = "https://na68.salesforce.com/")
got the same error.

if I create the token  running  rforcecom.login,  with api  apiVersion = "45.0" worked fine.
if I create the token running  rforcecom.login,  with api  apiVersion = "46.0" didn't work.

after create the token with the apiVersion="45.0" I may use sf_auth() without problem.

Is there any way to contro apiVersion from sf_auth() call?

based on the trials it seems  a problem with the apiVersion and my sales org right?

Regards.

**Comment by StevenMMortimer** [comment]
@pcorvalan Thanks for thoroughly checking all of that. My guess is that it's something with your org not handling v46. You can globally set the version of the API that all of the calls use by running this code right after loading the **salesforcer** library: 

```
library(salesforcer)
options(salesforcer.api_version = "45.0")

# you can confirm its set to v45 by running this code
getOption("salesforcer.api_version")

# then run
sf_auth()
sf_user_info()
```

**Comment by pcorvalan** [comment]
@StevenMMortimer 
library(salesforcer)
options(salesforcer.api_version = "45.0")

It works!! Thank your for your time and for develop this package! 

Regards.

**Comment by StevenMMortimer** [comment]
@pcorvalan Thanks for reporting it and testing it out. I'll include some language in the documentation to explain how to set the API version globally in case other people have a similar issue.
