### ISSUE TITLE
cannot get textarea fields through SOQL

### ISSUE THREAD

**Issue by djcher** [StevenMMortimer/salesforcer#25]
I'm using salesforcer:

session2 <- salesforcer::rforcecom.login(username, paste0(password, security_token), 
                                         apiVersion=getOption("salesforcer.api_version"))

I can connect to my SF repository and get field names for an object. the SQL statement "soql" below gets data only if I filter out field names that are "textarea". Otherwise the query hangs.

I'd like to have access to those textarea fields if possible.

FieldNames=getFieldNames(Object) %>% filter(!type=='textarea')
soql=paste('select', paste(FieldNames$name, collapse=','), 'from', Object)

**Comment by StevenMMortimer** [comment]
@djcher Can you provide a more complete version of the script you are using? Also, can you try turning on the `verbose=TRUE` argument in your call and including it in the issue. One more thing is that you need read and write access to those fields. Not saying I doubt you do, but just something to note.

Finally, any specific reason you are using `rforcecom.login()` vs. `sf_auth()`?

**Comment by StevenMMortimer** [comment]
@djcher I will close this issue. If you need more assistance just comment here again or open a different issue.

**Comment by djcher** [comment]
Sure thing thanks

——-
Daniel Cher
djcher@gmail.com
650-269-5763
