### ISSUE TITLE
oauth() closing problems

### ISSUE THREAD

**Issue by AleksanderPolitanski** [StevenMMortimer/salesforcer#28]
Hello,
I'm using oauth() function for authorisation purposes.
Problem is, that when I want to change enviornment from one staging to another,
I have to... reboot the computer. For some reason, deleting the .httr-oauth-salesforcer file
and .gitignore file doesn't help. R is still able to reconnect to salesforce enviornment.
Probably I'm doing something wrong.
But maybe it would be useful to add funcion like oauth.close() to the package, to be able to automatically clear the authorisation? 

Many thanks

**Comment by StevenMMortimer** [comment]
@AleksanderPolitanski With OAuth you use the browser to complete the authentication. It's possible that even if you delete the `.httr-oauth-salesforcer` file that it will be created again using your currently logged in session in your browser, which gets closed only after rebooting your computer. If you'd like to switch between environments use a token and not a cached file. This circumvents the browser based authentication every time you use the token (except when you initially create it). This will give you more control. Here is an example of how to do that: 

```
library(salesforcer)

# generate token from the sandbox environment and save it, cacheing is turned off
auth_details <- sf_auth(login_url = "https://test.salesforce.com", cache = FALSE)
saveRDS(auth_details$token, "my-sandbox-token.rds")

# generate a token from production and save it
auth_details <- sf_auth(login_url = "https://login.salesforce.com", cache = FALSE)
saveRDS(auth_details$token, "my-production-token.rds")

# now login, here is logging into sandbox
sf_auth(token = "my-sandbox-token.rds", cache = FALSE)

# here is logging into production
sf_auth(token = "my-production-token.rds", cache = FALSE)
```

This package's OAuth2.0 flow is almost exactly the same as the **googlesheets** R package which uses Google's OAuth. There is a great explanation about OAuth 2.0 tokens there which explains more of this: https://github.com/jennybc/googlesheets/blob/master/vignettes/managing-auth-tokens.md#where-do-tokens-come-from-the-oauth-20-flow

**Comment by AleksanderPolitanski** [comment]
Perfect, it works exactly as I wished. 
Many thanks.
