### ISSUE TITLE
Saving token for application

### ISSUE THREAD

**Issue by paulditterline** [StevenMMortimer/salesforcer#30]
Hello-

I found here that you can save the token by accessing the .state object:
https://rdrr.io/cran/salesforcer/man/sf_auth.html

However, when I do this locally after using sf_auth(), there is no such object - even though all my queries work.

I noticed this feature isn't covered in your vignette. Does it not work?

**Comment by paulditterline** [comment]
I was able to explicitly create the token using
```
my.state <- salesforce::salesforcer_state()
saveRDS(my.state$token, "token.rds")
```

Thanks!

**Comment by StevenMMortimer** [comment]
@paulditterline Thanks Paul for letting me know. I'll update the documentation.

**Comment by paulditterline** [comment]
You are correct - I've got a habit of doing that in long scripts so people know explicitly which package each function comes from (although in this case it's pretty obvious!). 

Thanks!
