### ISSUE TITLE
Clarification on sf_update success

### ISSUE THREAD

**Issue by ghareesh** [StevenMMortimer/salesforcer#36]
Hi ,
Does the status of sf_update function reflect the status as returned from salesforce after a particular filed gets updated?

I have a repeating scenario as follows in production code..

When a record gets created, there is a field which says "waiting for ML process". My R code runs every minute scanning this status and picks records whichever is waiting for my process.. Once my process is complete, it updates status to "processed by ML".  

Now couple of times for ~8-10 Hrs, I see same records get picked multiple times because the status change is not getting updated in salesforce..  The process log shows the data being sent out from process.. 

I am aware of **success** field in **sf_update** function..   Does this field reflect status returned by salesforce? 

Are there scenarios where despite success value being true, value in saleforce field doesnot get updated?

Your help is highly appreciated.. Let me know if you need any more elaborations

Thanks in advance

**Comment by StevenMMortimer** [comment]
@ghareesh The package simply passes data back and forth to Salesforce. If Salesforce returns success = true, then it's fair to assume that the operation was successful. There are a few points of failure that you can begin checking: 

1. Check that your update script is actually updating the fields you expect. You can test this by running the script with a small batch and then looking at the records in the Salesforce UI to see if they have the updated status of "processed by ML". 
2. Check that your R code that's running every minute is not getting "hung up". Is it possible that the script is not finishing or finishing too slowly and then another version of that same R process that gets spun up the next minute is picking them up as well? You want to try to ensure that your processes do not overlap, which can easily happen if you have a scheduled cron job that executes every minute.
3. My last thought is that somehow your queries might be getting cached. I cannot find good information from Salesforce on how query caching works so you may need to investigate more of that on your own.

**Comment by ghareesh** [comment]
Thanks Steven.. 
First two points are already taken care..  For point 1, I have tested functionality in UAT.. For point 2, I have a file lock in place.. Strange thing is that, from the logs, I see process was running every minute without any overlap.. 
I will check on query caching part..   
I observed this issue once previously, which got sorted by updating to 0.1.3.9.0000 package version of salesforcer from previous.. I was suspecting any issue in REST update, hence asked you.. But thanks for clarifying and  I understand it may not be a package issue per se..
