### ISSUE TITLE
Preserving file creation date, and last modified date, when uploading files 

### ISSUE THREAD

**Issue by rgustavs** [StevenMMortimer/salesforcer#39]
I am uploading files to SalesForce (sf_create_attachement) from a legacy system and want to retain the original file creation date. 

According to https://salesforce.stackexchange.com/questions/140868/preserving-file-creation-date-and-last-modified-date-when-uploading-files-to-c/140903 it is possible by 

Check Set audit field values for imported records

Step 1: You need to enable "Enable Set Audit Fields upon Record Creation and Update Records with Inactive Owners" User Permissions" permission from Setup-->Customize-->User Interface. This will allow you to set Created Date on a record.

Step 2: Also you need to give following permission to a user who is loading those data "Set audit fields, such as Created By and Last Modified By, when you create a record (API only)."

Is this something that is supported by SalesforceR 
Or do you propose another approach

Thanks for your great work!

**Comment by StevenMMortimer** [comment]
@rgustavs Thanks for letting me know about your use case. I only added the `sf_create_attachment()` function to the package yesterday and I have not finished testing, so I would recommend you use it cautiously. With that being said, it sounds like Step 1 and Step 2 are controls or permissions that you need to set in the UI before uploading the files, so they don't have anything to do with the package. Unless you are asking how to update those permissions programmatically via the Metadata API. In that case, there is another issue which discussing updating Profile permissions here: https://github.com/StevenMMortimer/salesforcer/issues/8#issuecomment-404029700. At some point I'd like to write more documentation around this aspect of the Metadata API so please feel free to contribute if you find something. Thanks.

**Comment by StevenMMortimer** [comment]
@rgustavs As a follow up, once you've configured "Enable Set Audit Fields" at the organization level and given API users the permission "Set Audit Fields upon Record Creation", then you can pass the 4 System Fields (`CreatedByID`, `CreatedDate`, `LastModifiedByID`, `LastModifiedDate`) just like you would any other field on a record. For example: 

```
library(salesforcer)
library(tidyverse)
sf_auth()

attachment_details <- tibble(Name = c("salesforcer.png"),
                             Body = system.file("help/figures", "salesforcer.png", 
                                                package="salesforcer"),
                             ContentType = c("image/png"),
                             CreatedByID = "0056A000000MPRjQAO",
                             CreatedDate = "2019-09-16T00:00:00.000Z",
                             LastModifiedByID = "0056A000000MPRjQAO",
                             LastModifiedDate = "2019-09-16T00:00:00.000Z",
                             ParentId = "0016A0000035mJ5")
attachment_records <- sf_create_attachment(attachment_details)
attachment_records
#> # A tibble: 1 x 2
#>  id                 success
#>  <chr>              <lgl>  
#>  00P3s00000WbVPPEA3 TRUE  
```

The images below are screenshots on how to configure your org to be able to change these system level fields. Here are the Salesforce instructions: https://help.salesforce.com/articleView?id=000334139&type=1&mode=1. They are similar to what you initially copied over from the StackExchange question.

<img width="659" alt="Screen Shot 2019-09-17 at 4 17 54 PM" src="https://user-images.githubusercontent.com/5299737/65076316-bf3f5080-d966-11e9-95aa-672f6d7f3c7c.png">

<img width="834" alt="Screen Shot 2019-09-17 at 4 13 11 PM" src="https://user-images.githubusercontent.com/5299737/65076220-8e5f1b80-d966-11e9-8a1d-78281acaaa16.png">

**Comment by rgustavs** [comment]
Wow, thanks for an amazingly fast response. If only were as fast and had your skills I would happily contribute more to your application then asking questions. 

Honestly, I thought I misunderstood github timestamps when I saw that the file was only a day old:  :) 

Keep up the great work!

**Comment by StevenMMortimer** [comment]
@rgustavs No problem. FYI: I finished testing the `sf_create_attachment()` function. To start using it you will need to install from GitHub using the command below. Please create an issue if you find any bugs or have questions. Thanks.

```
# install from GitHub
devtools::install_github("StevenMMortimer/salesforcer")
```

**Comment by rgustavs** [comment]
Boom! I can confirm it works. Thanks for clear instructions
