### ISSUE TITLE
Package cuts value off and rounds

### ISSUE THREAD

**Issue by 3lue** [StevenMMortimer/salesforcer#40]
Hey!

First of all: thanks for this package! It made it very easy for me and my team to fetch salesforce data. But we experience a problem and you probably can help us: we save the google client id (f.e.: "123456789.123456789") of our users into SF, but when we try to fetch it via salesforcer it seems that the package cuts some numbers off. Sometime we only get "123456789.12345", sometime "123456789.1234" and so on. The biggest problem is that it is rounding the last number, so it can go from "123456789.123456789" to "123456789.12346". 

![image](https://user-images.githubusercontent.com/4589085/66655044-b4ad6980-ec3b-11e9-84f1-0883f7eabd86.png)

Here I have an example with the ORGanizer for Salesforce Chrome Plugin. Thanks for your help!

**Comment by StevenMMortimer** [comment]
@3lue If you are using [`sf_query()`](https://stevenmmortimer.github.io/salesforcer/reference/sf_query.html) there is an argument called `guess_types` which you can set to `FALSE`. This will prevent the function from trying to cast the data using logic from the **readr** package. Note, that this will cause all data to be returned as characters so you will need to cast the remaining columns as needed.

**Comment by 3lue** [comment]
@StevenMMortimer thank you very much, that was the solution!
