### ISSUE TITLE
NULL Salesforce values causing Tibble error when listing object fields

### ISSUE THREAD

**Issue by jsallie** [StevenMMortimer/salesforcer#41]
I was receiving the below error on random objects when pulling object fields using sf_describe_object_fields. I traced it back to the function collapse_list_with_dupe_names, specifically "collapsed <- map_df(obj_field_dupes, as_tibble)". The dupe_field_names list contained lists with NULL values, so when converting to a tibble the error was thrown. 

I wasn't able to find a good work around on the tibble package, so I put together the below to simply replace any NULLs with NAs and it now works beautifully. 

collapsed <- map_df(obj_field_dupes, function(x) as_tibble(lapply(x, function(y) if(is.null(y)) NA else y)))

![image](https://user-images.githubusercontent.com/55643915/66682615-9ea3a700-ec43-11e9-8d20-bd7f16485bc9.png)

**Comment by awsad** [comment]
I had the same error, traced it back to the same function. While debugging wondered if someone else had already done the work so came here. Your solution works great! You should make a pull request for it!

**Comment by StevenMMortimer** [comment]
@jsallie @awsad Thanks for noting the issue. I believe this was fixed by this commit: https://github.com/StevenMMortimer/salesforcer/commit/60b9d5de9d4ead30e5072140a6a44c778669a19b

The fix will be on CRAN when the next minor version of the package is released there.
