### ISSUE TITLE
Why sf_auth() not works for 'Environnement Sandbox Partial'?

### ISSUE THREAD

**Issue by andirey** [StevenMMortimer/salesforcer#43]
I have credentials for Salesforce API for 'production' and 'sandbox' data sets
```r
library(salesforcer)

SF_USER_NAME <- "sf_user_name"
SF_PASSWORD <- "sf_password"
SF_TOKEN <- "sf_token"

sf_auth(username = SF_USER_NAME, password = SF_PASSWORD, security_token = SF_TOKEN)
```

The code is running fine for "production" settings and fails for "Environnement Sandbox Partial" ("sandbox") settings. The most strange thing that "sandbox" settings work for Python code.

Any ideas on how to fix this bug for 'sandbox'?

Thanks

**Comment by andirey** [comment]
Here is a solution I found at the end

```r
sf_auth(login_url = "https://test.salesforce.com/",  
        username = SF_USER_NAME, password = SF_PASSWORD, security_token = SF_TOKEN)
```

The default settings seem equal to "https://login.salesforce.com" when for for "sandbox" it should be "https://test.salesforce.com/"

Hope it will be useful as well

**Comment by StevenMMortimer** [comment]
For future reference, users can log into a "Sandbox" or "Dev" environment one of two ways: 

1. Set the `login_url` argument inside the `sf_auth()` function to whatever URL you use when logging into your environment (e.g. https://test.salesforce.com vs. https://login.salesforce.com)
2. Set the global option in the **salesforcer** package by including the following at the top of your scripts, but after loading the package: 
```
options(salesforcer.login_url = "https://test.salesforce.com")
```
