### ISSUE TITLE
Parsing error with error messages in upsert

### ISSUE THREAD

**Issue by dahenn** [StevenMMortimer/salesforcer#44]
When doing an upsert, I receive a warning with specific error messages. However, in the object created by `sf_upsert`, the error column is type logical and filled with NA.

See warning: 

>   upsert <- sf_upsert(io_sf, 'Product_Component__c', 'Product_Component_ID__c', api_type = 'Bulk 1.0')
> 
> Warning: 4 parsing failures.
> 
>  row   col           expected                                                                                           actual         file
> 1519 Error 1/0/T/F/TRUE/FALSE DUPLICATE_VALUE:Duplicate external id specified: 63-12706-10-09360-76:Product_Component_ID__c -- literal data
> 1522 Error 1/0/T/F/TRUE/FALSE DUPLICATE_VALUE:Duplicate external id specified: 63-12706-10-09360-76:Product_Component_ID__c -- literal data
> 3832 Error 1/0/T/F/TRUE/FALSE DUPLICATE_VALUE:Duplicate external id specified: 63-74401-10-09360-76:Product_Component_ID__c -- literal data
> 3833 Error 1/0/T/F/TRUE/FALSE DUPLICATE_VALUE:Duplicate external id specified: 63-74401-10-09360-76:Product_Component_ID__c -- literal data

**Comment by StevenMMortimer** [comment]
The error is generated by the **readr** package which assumes the datatypes of columns as they are read back into R from Salesforce. You can read about the error message here (https://readr.tidyverse.org/articles/readr.html#rectangular-parsers). 

Correct me if I'm wrong, but your results are returned and it's just a warning message, not an error that stops the entire process? The only way to fix would be to hard-code the column type specification for bulk jobs. I think this is possible for Bulk 1.0, but not Bulk 2.0 which returns all of the different columns that were originally passed into the function.
