### ISSUE TITLE
HTTR OAuth Issue

### ISSUE THREAD

**Issue by sgourkar** [StevenMMortimer/salesforcer#45]
I have an R script that I'm trying to run on a regular schedule in Windows 10.  Whenever I try to execute script from the Windows command line, I receive the following error: 

**Error: Failed to create local cache ('.httr-oauth-salesforcer')**

I'm not quite sure how to address this issue. Do I have to authenticate to Salesforce from the command line as well? Whenever I execute the script from RStudio, it successfully runs.

Thanks in advance for your help.

I'm running R-3.6.2 on Windows 10 and I'm trying to upsert data using the Bulk 2.0 api.

**Comment by StevenMMortimer** [comment]
@sgourkar First, check that there is a cached token file (`.httr-oauth-salesforcer`) in the working directory of your project. If the answer is yes, then it's possible that while your script is executing it's not using the same working directory. I'd recommend using some combination of `message()` and `setwd()` to troubleshoot what is the working directory while your script is executing. There are quite a few resources on StackOverflow to help: 

https://stackoverflow.com/questions/1815606/determine-path-of-the-executing-script

https://stackoverflow.com/questions/13672720/r-command-for-setting-working-directory-to-source-file-location-in-rstudio

**Comment by sgourkar** [comment]
Thanks for the reply! It turns out I was not pointing to the cached token file. Once I did that using sf_auth() I was able to get my script up and running with the task scheduler.
