### ISSUE TITLE
Bad Request (HTTP 400). Failed to get an access token.

### ISSUE THREAD

**Issue by alanmiyakawa** [StevenMMortimer/salesforcer#47]
I am receiving the following error message:

Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Bad Request (HTTP 400). Failed to get an access token.

This is the code that I am running:

suppressWarnings(suppressMessages(library(dplyr)))
library(salesforcer)
sf_auth()

1. After running this code, a new browser window opens and I enter our custom domain (to our full Salesforce sandbox). 
2. This then takes me to okta (our single sign-on platform) and I sign-in using my okta credential. 
3. I then click "Allow"
4. I am then taken to a page that says "Authentication complete. Please close this page and return to R."
5. When I return to R, I get the error message: Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  :   Bad Request (HTTP 400). Failed to get an access token.

I am using salesforcer version 0.1.3.9.000 and R version 3.6.1.

I'm not sure what I am doing wrong. Am I missing a step?

**Comment by StevenMMortimer** [comment]
@alanmiyakawa Could you try passing the `login_url` argument in `sf_auth()` prior to the authorizing in the browser?
https://stevenmmortimer.github.io/salesforcer/reference/sf_auth.html

**Comment by alanmiyakawa** [comment]
Adding that argument solved the issue for me. Thank you so much!
