### ISSUE TITLE
API version requirement for sf_query_bulk

### ISSUE THREAD

**Issue by abhigampa123** [StevenMMortimer/salesforcer#48]
Hi Steve, this is more of a question than an issue. 
I am using sf_query_bulk to extract data from Bulk API. But it errors out as "JSON content type is not supported". I see from the logging that it is using API version 35.0. It works fine when I am using it with my personal Salesforce developer account. (I installed package from CRAN in both the environments I mentioned.) One difference I see is that developer account's end points use API version 47.0. I tried to overwrite the client's API to 47.0 by using Rforcecom.login but it is not working. Does this package only support latest API versions and upgrading API version is something that needs to be done at the SalesForce administrator level? 
Below is the query I am using in both the environments:
df <- sf_query_bulk(soqlQuery,
                          object_name = "Account",
                          queryall = FALSE,
                          guess_types = TRUE,
                          api_type = "Bulk 1.0",
                          interval_seconds = 5,
                          max_attempts = 100,
                          verbose = TRUE)

(This is my first encounter with Salesforce APIs, appreciate your help and it's been a great experience working with this library)

**Comment by StevenMMortimer** [comment]
@abhigampa123 You can set the API version as session option variable like this: 

```
library(salesforcer)
# see the package default API version
getOption("salesforcer.api_version")

# this will force all calls to be against the version "47.0"
options(salesforcer.api_version = "47.0")
```

You referenced "Rforcecom.login", I'd recommend using `sf_auth()` to authenticate instead of the backward compatible **RForcecom** functions.
