### ISSUE TITLE
Some columns not available to rforcecom.query

### ISSUE THREAD

**Issue by naltmann** [StevenMMortimer/salesforcer#49]
I am able to successfully run a SOQL query like "SELECT Id, RelatedToId FROM EmailMessage" from the Salesforce Developer Console and the official Salesforce CLI.

When I run the same SOQL query through salesforcer (or Rforcecom) I get the message "No such column 'RelatedToId' on entity 'EmailMessage'." That error is consistent with the available fields I see from from the rforcecom.getObjectDescription(session, "EmailMessage") command, but I can't figure out why it is that the RelatedToId field is available from some query methods, but not Salesforcer.

**Comment by arp3ggio** [comment]
What is your code to construct the query? Is it similar to the example provided here?
https://github.com/StevenMMortimer/salesforcer#query

This is the format I've been using:
```
# devtools::install_github("StevenMMortimer/salesforcer")
library(salesforcer)
library(dplyr)
library(glue)
sf_object <- "User"
api_type_input <- "REST"
fields <- c(
  "Name,
Email,
Id"
)
query_result <- glue_sql(glue("SELECT {fields} FROM {sf_object}")) %>%
  sf_query(
    sf_object,
    guess_types = FALSE,
    api_type = api_type_input
  )
```

**Comment by StevenMMortimer** [comment]
@naltmann Try `RelatedToId`. 

According to the documentation of the EmailMessage object, `RelatedToId` exists, but not `RelatedTo`. I assume the other programs you are using are able to resolve `RelatedTo` to the name or the id of the account, contact, opportunity, etc. for you but I think with the API SOQL you'll need to specify `RelatedToId` instead.

EmailMessage Documentation: https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_emailmessage.htm
