### ISSUE TITLE
Update picklist

### ISSUE THREAD

**Issue by Btibert3** [StevenMMortimer/salesforcer#50]
Building on my previous question from two years ago(https://github.com/StevenMMortimer/salesforcer/issues/7), I think I am still lost as to how we would update an existing field's picklist values.  I am attempting to read the docs and map that to the R way of doing things here, but I must be missing something obvious.  Your docs  and package are absolutely fantastic, so what would you recommend that I look for a better path on adding to/or deleting from an existing picklist on a custom field.  

I hope all is well on your end!

**Comment by StevenMMortimer** [comment]
Hey @Btibert3! I think the process for updating a picklist field would be the same structure as creating it in #7 , only this time you'd need to use `sf_update_metadata()` instead of `sf_create_metadata()`.

Let me know if this works: 

```
cf3 <- list(fullName = 'Account.MessageIntent__c',
            label = 'Message Intent', 
            type = 'Picklist',
            valueSet = list(valueSetDefinition=list(sorted="true", 
                                                    value=list(fullName="greet", default="true", label="Greet"), 
                                                    value=list(fullName="affirm", default="false", label="Affirm"))))
cf3_result <- sf_update_metadata(metadata_type = 'CustomField', metadata = cf3, verbose = TRUE)
```

**Comment by Btibert3** [comment]
I will take a look, you are the best.  I am really struggling with mapping the docs to R, but your library is absolutely amazing.  When normalcy resumes, would love to catch up.

**Comment by StevenMMortimer** [comment]
@Btibert3 Going to close this issue for now. Thanks for reaching out to clarify. Create another issue or append here if you still have questions.
