### ISSUE TITLE
SOQL support for querying last "N" hours modified records

### ISSUE THREAD

**Issue by ghareesh** [StevenMMortimer/salesforcer#51]
Hi,..
Trying to query records modified in last 1 hour as an example..
Code is scheduled to execute every hour.. So at 4 PM, it should fetch all 3PM onward records. For 12AM, it should fetch 11PM records onwards and so on

Trying below gives error ,
 LastModifiedDate>= :Datetime.now().addMinutes(-60)")
that,
**,Bind variables only allowed in Apex code**

Is there a fix for this or an alternate option. 

a. If I use, 
LastModifiedDate = TODAY AND 
HOUR_IN_DAY(LastModifiedDate) >",hr)

with 
hr = hour(with_tz(Sys.time(),tzone = "America/Los_Angeles"))-1

it wont work for 12:00 AM time window.. 

Would appreciate any workaround or fix here..

**Comment by StevenMMortimer** [comment]
@ghareesh You can pass in a formatted timestamp. Like this: 

```
# one hour from current time (represented in UTC)
one_hour_ago <- lubridate::as_datetime(Sys.time()) - lubridate::hours(1)

# match the datetime format required by SOQL
formatted_for_soql <- format(one_hour_ago, "%Y-%m-%dT%H:%M:%SZ")

# query the records using the formatted datetime string
sf_query(
   sprintf("SELECT id, name FROM Account WHERE LastModifiedDate = %s",
           formatted_for_soql)
)
```

If you need the timestamp to be rounded down to the hour, then use the `floor_date()` function from the **lubridate** package like this: 

```
current_timestamp <- lubridate::as_datetime(Sys.time())
# > [1] "2020-05-02 18:14:27 UTC"

one_hour_ago <- current_timestamp - lubridate::hours(1)
# > [1] "2020-05-02 17:14:27 UTC"

# not truncated to the top of the hour
format(one_hour_ago, "%Y-%m-%dT%H:%M:%SZ")
# > [1] "2020-05-02T17:14:27Z"

# truncated to the top of the hour
format(lubridate::floor_date(one_hour_ago, "hours"), "%Y-%m-%dT%H:%M:%SZ")
# > [1] "2020-05-02T17:00:00Z"
```

Here is a link to the SOQL reference that shows the required datetime format: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm

**Comment by ghareesh** [comment]
> @ghareesh You can pass in a formatted timestamp. Like this:
> 
> ```
> # one hour from current time (represented in UTC)
> one_hour_ago <- lubridate::as_datetime(Sys.time()) - lubridate::hours(1)
> 
> # match the datetime format required by SOQL
> formatted_for_soql <- format(one_hour_ago, "%Y-%m-%dT%H:%M:%SZ")
> 
> # query the records using the formatted datetime string
> sf_query(
>    sprintf("SELECT id, name FROM Account WHERE LastModifiedDate = %s",
>            formatted_for_soql)
> )
> ```
> 
> If you need the timestamp to be rounded down to the hour, then use the `floor_date()` function from the **lubridate** package like this:
> 
> ```
> current_timestamp <- lubridate::as_datetime(Sys.time())
> # > [1] "2020-05-02 18:14:27 UTC"
> 
> one_hour_ago <- current_timestamp - lubridate::hours(1)
> # > [1] "2020-05-02 17:14:27 UTC"
> 
> # not truncated to the top of the hour
> format(one_hour_ago, "%Y-%m-%dT%H:%M:%SZ")
> # > [1] "2020-05-02T17:14:27Z"
> 
> # truncated to the top of the hour
> format(lubridate::floor_date(one_hour_ago, "hours"), "%Y-%m-%dT%H:%M:%SZ")
> # > [1] "2020-05-02T17:00:00Z"
> ```
> 
> Here is a link to the SOQL reference that shows the required datetime format: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm



Thanks a lot Steven.. You rock..

**Comment by ghareesh** [comment]
Thanks a lot Steven.. You rock..
