### ISSUE TITLE
Updating campaigns

### ISSUE THREAD

**Issue by barnabe** [StevenMMortimer/salesforcer#52]
This is great tool. I don't see a way to interact with campaigns. Is this possible? or planned?

**Comment by StevenMMortimer** [comment]
@barnabe Thanks! Could you elaborate on your use case with Campaigns? The package allows you to do many different things related to the Campaign object and other related objects, including email triggers and other notifications. It would be helpful to understand what you're envisioning. Thanks!

**Comment by barnabe** [comment]
Hi Steven, Thank you for your answer. Sorry if i missed it.. but i would just like to add contacts to leads to existing campaigns.

**Comment by StevenMMortimer** [comment]
@barnabe Yes, you can definitely do that. You just need to use `sf_create()` with the right Ids and objects in Salesforce that store that data. I am a little busy right now to pull together complete code example, but I'll check back in day or two to see where you're at. Thanks!

**Comment by barnabe** [comment]
Thank you! I just needed a bit of encouragement.. 

Here is my MRE

`campaign_dat=tibble(CampaignId="7012r000000--------",
                    ContactId="0031000001A------",
                    CurrencyIsoCode="USD",
                    Status="Registered")
sf_create(campaign_dat, 
            fields=c("CampaignId", "ContactId","CurrencyIsoCode","Status"), 
            object_name="CampaignMember")`

which gives 
`> sf_create(campaign_dat, 
+             fields=c("CampaignId", "ContactId","CurrencyIsoCode","Status"), 
+             object_name="CampaignMember")
# A tibble: 1 x 2
  id                 success
  <chr>              <lgl>  
1 00v2r000000Y7g9AAC TRUE   
`
Thanks again!
