### ISSUE TITLE
api_type = "Bulk 1.0" (InvalidSessionId: Unable to find session id

### ISSUE THREAD

**Issue by segoldma** [StevenMMortimer/salesforcer#6]
Great package so far. Looking forward to the Reports & Dashboard APIs.

Was playing around with creating contacts, and got an error message when passing api_type="Bulk 1.0" through the sf_create() function . When removing the api_type argument, the records were created successfully.

``` r
library(salesforcer)

# Connect to Salesforce
sf_auth(username = "[redacted]"
        password = "[redacted]"
        security_token = "[redacted]"
        login_url = 'https://test.salesforce.com/')

# View User Info (Checking the authentication... redacted for this example)
sf_user_info()
#> $aboutMe
#> NULL

#> $displayName
#> [1] "Seth Goldman"

#> $username
#> [1] "[redacted]"

# Use Bulk API to create two new contacts
n <- 2
new_contacts <- tibble(FirstName = rep("Test",n),
                       LastName = paste0("Contact-Create-",1:n))
#> Error in tibble(FirstName = rep("Test", n), LastName = paste0("Contact-Create-", : could not find function "tibble"

create_contacts <- sf_create(new_contacts, object_name="Contact",api_type = "Bulk 1.0")
#> Error in is.data.frame(input_data): object 'new_contacts' not found
```

Created on 2018-07-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by StevenMMortimer** [comment]
Hey @segoldma! In your reprex I'm seeing the error `could not find function "tibble"` and `object 'new_contacts' not found` prior to making the `sf_create()` call. 

Could you try adding `library(dplyr)` up with the `library(salesforcer)` call at the top of your script just to make sure it's not an issue with the `new_contacts` data.frame not being created before you attempt to send over to Salesforce?

**Comment by StevenMMortimer** [comment]
@segoldma I was able to reproduce and will work on it. I'll let you know when the fix is up on GitHub. You could then install from GitHub or wait until v0.1.3 is released on CRAN. 

The issue is a bug when using the username-password authentication along with Bulk 1.0 API. The REST, SOAP, or Bulk 2.0 APIs work with username-password authentication. If you really want to use the Bulk 1.0 API, it does work when using OAuth 2.0 authentication. Just authenticate using `sf_auth(login_url="https://test.salesforce.com")` and follow the browser prompts.

**Comment by segoldma** [comment]
That's great, thanks for the explanation.  Will give OAuth 2.0 a try.

**Comment by StevenMMortimer** [comment]
I was just able to push the [fix](https://github.com/StevenMMortimer/salesforcer/commit/99b592db313678d69446434b188c8840e7a38152#diff-def4dc6ddc8856a16bdac082f078254f) and it passed the build checks. If you want to try it out, just re-install the package using: `devtools::install_github("StevenMMortimer/salesforcer")`.

**Comment by segoldma** [comment]
Works great! Thanks again. Have a good weekend.

**Comment by Btibert3** [comment]
👍

**Comment by Btibert3** [comment]
👍
