### ISSUE TITLE
Metadata Custom Field - Create Picklist

### ISSUE THREAD

**Issue by Btibert3** [StevenMMortimer/salesforcer#7]
It appears that picklists are deprecated, or will be, in the API.  That said, I simply want to create a custom field that acts like a single picklist via the APi.  

I have attempted many variants, but the latest is:

```
cf3 <- tibble(fullName=c(paste0(base_obj_name, '__c.MessageIntent__c')),
                        label=c('Message Intent'), 
                        type = 'valueSet',
                        valueName = c("greet", "affirm"))
cf3_result <- sf_create_metadata(metadata_type = 'CustomField', 
                                 metadata = cf3)

```

and seemingly no matter how many combinations of parameters, I get some version of this error:

```
You must specify either picklist, globalPicklist, or valueSet
```

Perhaps its something obvious that I am overlooking, but any help will be appreciated.

**Comment by StevenMMortimer** [comment]
It looks like there were some changes for defining picklists from v37.0 to v38.0. I haven't tested this out yet, but I assume the input needs to be a list structure in order to get the XML nested as it needs to be. Something like: 

```
cf3 <- list(fullName=paste0(base_obj_name, '__c.MessageIntent__c'),
            label='Message Intent', 
            type = 'Picklist',
            valueSet = list(valueSetName=MessageIntents, 
                            valueSetDefinition=list(value="greet", 
                                                    value="affirm")))
```


Adding some references here:
 - https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_field_types.htm
 - https://salesforce.stackexchange.com/questions/186764/create-picklist-using-metadata-api?rq=1
 - https://salesforce.stackexchange.com/questions/194444/create-update-global-picklist-using-tooling-api-or-metadata-api/194446

**Comment by Btibert3** [comment]
Thanks for this, I tried the code above and got an error saying:

```
> cf3_result
# A tibble: 1 x 4
  errors.message                                          errors.statusCode  fullName    success
  <chr>                                                   <chr>              <chr>       <chr>  
1 At least one value is required to create this picklist. FIELD_INTEGRITY_E… ChatMessag… false  
```

I will poke around later today, but I appreciate your help.  This package is absolutely fantastic.

**Comment by StevenMMortimer** [comment]
Was messing around for a bit and got a different error message: 

```
cf3 <- list(fullName = 'Account.MessageIntent2__c',
            label = 'Message Intent', 
            type = 'valueSet',
            valueSet = list(valueSetName='MessageIntents', 
                            valueSetDefinition=list(value=list(fullName="greet", default="true", label="Greet"),
                                                    value=list(fullName="affirm", default="false", label="Affirm"),
                                                    sorted="true"
                                                    )))
cf3_result <- sf_create_metadata(metadata_type = 'CustomField', metadata = cf3, verbose = TRUE)

> cf3_result
# A tibble: 1 x 4
  errors.message                                                                              errors.statusCode         fullName                  success
  <chr>                                                                                       <chr>                     <chr>                     <chr>  
1 You cannot define picklist, globalPicklist, and valueSet. Only one definition is permitted. FIELD_INTEGRITY_EXCEPTION Account.MessageIntent2__c false 
```

**Comment by StevenMMortimer** [comment]
@Btibert3 I finally got it working thanks to [this link](https://salesforce.stackexchange.com/questions/176517/create-picklist-field-with-picklist-values?rq=1).

Here is code that works: 

```
cf3 <- list(fullName = 'Account.MessageIntent__c',
            label = 'Message Intent', 
            type = 'Picklist',
            valueSet = list(valueSetDefinition=list(sorted="true", 
                                                    value=list(fullName="greet", default="true", label="Greet"), 
                                                    value=list(fullName="affirm", default="false", label="Affirm"))))
cf3_result <- sf_create_metadata(metadata_type = 'CustomField', metadata = cf3, verbose = TRUE)

> cf3_result
# A tibble: 1 x 2
  fullName                 success
  <chr>                    <chr>  
1 Account.MessageIntent__c true   
```

It's funny that as soon as you add the argument `valueSetName` along with the `valueSetDefinition` then the call bombs with the error you showed in your first post. I believe it's because if you provide a `valueSetName`, then you are asking Salesforce to create a valueset, but the type you've specified is `'Picklist'` and it can't do both at the same time. So you basically have to drop the name associated with the valueset. That should be fine because if you want the valueset to be persistent, then you should be creating a GlobalValueSet and referencing that when you create the custom field and not trying to pass the values into it while creating.

**Comment by Btibert3** [comment]
I am not sure I follow 100% of what you found, but this is fantastic.  Thanks for diving into this!

**Comment by miteshsura** [comment]
@Btibert3 , did you figure out solution to this? I am getting similar error message when using Metadata API within Salesforce to create picklist fields. I am on v40. Please see this links for more information

- https://salesforce.stackexchange.com/questions/186764/create-picklist-using-metadata-api
- https://salesforce.stackexchange.com/questions/176517/create-picklist-field-with-picklist-values

Any help is appreciated.

**Comment by Btibert3** [comment]
I did, see the code sample above.  Does that approach not work for you?

**Comment by miteshsura** [comment]
@Btibert3 , I was not providing valueSetName to begin with but still getting "_You must specify either picklist, globalPicklist, or valueSet_" error message. I am trying to create fieldset in Salesforce dynamically using Metadata API. See the code below, it is same what everyone has mentioned, not sure where it is going wrong. 

```
MetadataService.CustomField customField = new MetadataService.CustomField();
customField.fullName = 'Opportunity.Segment1__c';
customField.label = 'Segment';
customField.type_x = 'Picklist';
customField.description = '';   

//value
List<MetadataService.CustomValue> values = new List<MetadataService.CustomValue>();
MetadataService.CustomValue v1 = new MetadataService.CustomValue();
v1.fullName = 'SegmentA';
values.add(v1);

//valueSetDefinition
MetadataService.ValueSetValuesDefinition vsd = new MetadataService.ValueSetValuesDefinition();
vsd.value = values;
vsd.sorted = true;

//valueSet
MetadataService.ValueSet vs = new MetadataService.ValueSet();
vs.valueSetDefinition = vsd;

//Set valueSet
customField.valueSet = vs;
```

**Comment by StevenMMortimer** [comment]
@miteshsura Are you using the R programming language? What you've posted appears to be Java. Regardless of the language, check the XML that your process creates. It should look like this: 

```
<Metadata xmlns:ns2="http://soap.sforce.com/2006/04/metadata" xsi:type="ns2:CustomField">
    <fullName>Account.MessageIntent__c</fullName>
    <label>Message Intent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
              <fullName>greet</fullName>
              <default>true</default>
              <label>Greet</label>
            </value>
            <value>
              <fullName>affirm</fullName>
              <default>false</default>
              <label>Affirm</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</Metadata>
```
