### ISSUE TITLE
Feature Request: update attachments

### ISSUE THREAD

**Issue by richardjwood** [StevenMMortimer/salesforcer#79]
### Issue description

I'd like to be able to update attachments using salesforcer. It appears there's a commented-out line in the sf_create_attachment code for sf_update_attachment, and there are references in the documentation to an update command. Setting the control operation to update in sf_create_attachment doesn't work as there is an override. 

In case it matters: the use case is for downloading attachments (such as TXT / EVTX, and other uncompressed files), zipping them, and re-uploading them with .zip added to the filename.

**Comment by StevenMMortimer** [comment]
@richardjwood Thanks for sharing the use case and request. I'll plan to include in the release of v0.2.1 to CRAN in the next week or two that will also fix a bug introduced in v.0.2.0, so I should be able to get this incorporated soon. Will keep you posted.

**Comment by StevenMMortimer** [comment]
@richardjwood Thanks again for suggesting the enhancement. It's in the repo now if you would like to install from there using:

```r
# install.packages("remotes")
remotes::install_github("StevenMMortimer/salesforcer")
```

I'm waiting to publish v0.2.1 to CRAN until {dplyr 1.0.2} is released because there's a bug in how `dplyr::bind_rows()` is working in {dplyr 1.0.1}.
