### ISSUE TITLE
Update install instructions in readme

### ISSUE THREAD

**Issue by danwwilson** [StevenMMortimer/salesforcer#83]
### Issue description

The install instructions for the GitHub version fail now that you've moved away from a `master` branch to a `main` branch.

If you use `devtools::install_github("StevenMMortimer/salesforcer")` it throws the following error:

```
> Downloading GitHub repo StevenMMortimer/salesforcer@master
  Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
    cannot open URL 'https://api.github.com/repos/StevenMMortimer/salesforcer/tarball/master'
```

You may wish to update the install instructions to make use of the `ref` parameter like this:
`remotes::install_github("stevenmmortimer/salesforcer", ref = "main")`

I've also suggested the `remotes` package as it usually has less dependancies than dev tools.

Thanks for such a helpful package in working with salesforce.

**Comment by StevenMMortimer** [comment]
@danwwilson Thanks for the heads up! It looks like the default `ref` argument in `devtools::install_github()` is "master", but for "HEAD" for `remotes::install_github()` so whatever the default branch is, it will use that. Then I don't think you'll even need to specify `ref = "main"`.
