### ISSUE TITLE
Error in check_dots_used(action = warn) : unused argument (action = warn)

### ISSUE THREAD

**Issue by FabioBosc** [StevenMMortimer/salesforcer#92]
soql <- "SELECT Id,
                FirstName, 
                LastName
         FROM Contact LIMIT 10"

queried_records <- sf_query(soql) 
queried_records
**Error in check_dots_used(action = warn) : unused argument (action = warn)**

Hi,
I have this error.
What I have to do?

Thank you in advance for your help
Fabio

**Comment by StevenMMortimer** [comment]
@FabioBosc Can you double check the version of {tidyverse} and {ellipsis} packages that you have installed. Check this thread for how some others have resolved the issue: https://stackoverflow.com/questions/62998999/basic-dyplr-functions-give-an-error-check-dots-used
