### ISSUE TITLE
Datetime columns break internal sf_get_job_records_bulk_v2

### ISSUE THREAD

**Issue by JoshRosenstein** [StevenMMortimer/salesforcer#95]
https://github.com/StevenMMortimer/salesforcer/blob/7751e6ccf76550048f514e7757accb94d6acb2a6/R/bulk-operation.R#L1263
``` R
Error in match.fun(paste0("as.", class(base_class_df[[x]]))) : 
  'paste0("as.", class(base_class_df[[X[[i]]]]))' is not a function, character or symbol
```
Looks to be when a column of datetime  ( class= "POSIXct" "POSIXt" ) will bust match.fun. 
ie: 
```
match.fun(class(Sys.time()))("")
```

**Comment by JoshRosenstein** [comment]
BTW, I tried to pass in `combine_record_types=FALSE` within `sf_upsert`, to quickly bypass this issue,  but that argument does not get passed down into `sf_get_job_records_bulk`  (possibly another issue?).

**Comment by StevenMMortimer** [comment]
@JoshRosenstein To test a quick workaround, does setting `bind_using_character_cols=FALSE` work? I assume you are passing `api_type="Bulk 2.0" to `sf_upsert()`?

**Comment by JoshRosenstein** [comment]
@StevenMMortimer  
Yes using sf_upsert Bulk 2.0,
Just tested and `bind_using_character_cols` does not work. I actually dont see where where that setting would come to play within `sf_get_job_records_bulk_v2`, function.

**Comment by StevenMMortimer** [comment]
@JoshRosenstein Sounds good to switch to Bulk 1.0 for now. Thanks for reporting the issue. I'll look into it when I have some more time.
